import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowUpRight, BarChart3, Check, ChevronRight, Cloud, Code2, Layers3, Link2, Menu, Network, ShieldCheck, Sparkles, X } from 'lucide-react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { services, industries, processSteps } from './data'
import type { Service, Article } from './data'

const iconMap: Record<string, typeof Code2> = { code: Code2, layers: Layers3, link: Link2, cloud: Cloud, chart: BarChart3, spark: Sparkles, shield: ShieldCheck }

export function Icon({ name }: { name: string }) { const IconComponent = iconMap[name] ?? Network; return <IconComponent size={20} strokeWidth={1.8} aria-hidden="true" /> }

export function Header() {
  const [open, setOpen] = useState(false)
  const nav = [['Services', '/services'], ['Solutions', '/solutions'], ['Industries', '/industries'], ['Our Process', '/process'], ['Teams', '/teams'], ['About', '/about'], ['Insights', '/insights'], ['Contact', '/contact']]
  return <header className="site-header"><a className="skip-link" href="#main">Skip to content</a><div className="nav-wrap"><Link className="brand" to="/" onClick={() => setOpen(false)}><span className="brand-mark">P</span><span>POLCEBLAZER<span className="brand-small"> LLC</span></span></Link><button className="menu-toggle" aria-expanded={open} aria-controls="main-nav" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}<span className="sr-only">{open ? 'Close menu' : 'Open menu'}</span></button><nav id="main-nav" className={open ? 'main-nav open' : 'main-nav'} aria-label="Primary navigation">{nav.map(([label, href]) => <NavLink key={href} to={href} onClick={() => setOpen(false)}>{label}</NavLink>)}<Link className="button button-small" to="/contact" onClick={() => setOpen(false)}>Start a Project <ArrowUpRight size={16} /></Link></nav></div></header>
}

export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link className="brand footer-brand" to="/"><span className="brand-mark">P</span><span>POLCEBLAZER<span className="brand-small"> LLC</span></span></Link><p className="footer-copy">Engineering technology. Improving operations.</p><p className="fine-print">Practical software engineering and technology consulting for better business systems.</p></div><div><h3>Capabilities</h3>{services.slice(0, 4).map(s => <Link key={s.title} to="/services">{s.title}</Link>)}</div><div><h3>Company</h3>{['About', 'Our Process', 'Insights', 'Contact'].map(label => <Link key={label} to={`/${label === 'Our Process' ? 'process' : label.toLowerCase()}`}>{label}</Link>)}<Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms of Use</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} POLCEBLAZER LLC</span><span>LinkedIn: [Company profile placeholder]</span></div></footer> }

const pageHeroImages: Record<string, string> = { capabilities: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=85', outcomes: 'https://images.unsplash.com/photo-1454165205744-3b78555e5572?auto=format&fit=crop&w=1200&q=85', industries: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=85', 'our process': 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1200&q=85', 'our team': 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85', 'about polceblazer': 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=85', insights: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=85', 'start a project': 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=85', 'legal template': 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=1200&q=85', educational: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=85' }
export function PageHero({ eyebrow, title, text, image }: { eyebrow: string; title: string; text: string; image?: string }) { const imageKey = eyebrow.toLowerCase().split(' · ')[0]; const heroImage = image ?? pageHeroImages[imageKey] ?? pageHeroImages.insights; return <section className="page-hero"><div className="container page-hero-grid"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div><figure className="page-hero-media"><img src={heroImage} alt="" /></figure></div></section> }
export function SectionHeading({ eyebrow, title, text, align = 'left' }: { eyebrow?: string; title: string; text?: string; align?: 'left' | 'center' }) { return <div className={`section-heading ${align}`}>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{text && <p>{text}</p>}</div> }
export function CTA({ title = 'Turn a business priority into an executable next step.', text = 'Tell us about the performance gap, operating constraint, or strategic outcome that needs attention. We will help you frame a practical path forward.' }: { title?: string; text?: string }) { return <section className="cta-band"><div className="container cta-inner"><div><span className="eyebrow">Start a conversation</span><h2>{title}</h2><p>{text}</p></div><Link className="button button-light" to="/contact">Start a Project <ArrowUpRight size={17} /></Link></div></section> }
export function ServiceCard({ service }: { service: Service }) { return <article className="service-card"><div className="card-icon"><Icon name={service.icon} /></div><h3>{service.title}</h3><p>{service.description}</p><Link className="text-link" to="/services">Explore service <ChevronRight size={16} /></Link></article> }
export function IndustryCard({ item }: { item: { title: string; description: string } }) { return <article className="industry-card"><span className="industry-number">0{industries.indexOf(item) + 1}</span><h3>{item.title}</h3><p>{item.description}</p><Link className="text-link" to="/industries">View industry <ChevronRight size={16} /></Link></article> }
export function ProcessTimeline() { return <div className="timeline">{processSteps.map(([title, text], index) => <div className="timeline-step" key={title}><div className="step-number">0{index + 1}</div><div><h3>{title}</h3><p>{text}</p></div></div>)}</div> }
const articleImages: Record<string, string> = { 'Operating Model': 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=85', Transformation: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=900&q=85', 'Technology Strategy': 'https://images.unsplash.com/photo-1454165205744-3b78555e5572?auto=format&fit=crop&w=900&q=85', 'Connected Operations': 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=85', 'Organizational Capability': 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=85', 'Data Governance': 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=85' }
export function ArticleCard({ article }: { article: Article }) { return <article className="article-card"><div className="article-art"><img src={articleImages[article.category] ?? articleImages['Operating Model']} alt="" /><span>{article.category}</span></div><div className="article-content"><div className="article-meta">{article.date} <span>•</span> {article.readTime}</div><h3>{article.title}</h3><p>{article.excerpt}</p><Link className="text-link" to={`/insights/${article.slug}`}>Read article <ArrowUpRight size={16} /></Link></div></article> }

export function ContactForm() {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  const [error, setError] = useState('')
  async function submitProjectInquiry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (status === 'loading') return; const form = event.currentTarget; if (!form.checkValidity()) { setError('Please complete the required fields and check your email address.'); form.reportValidity(); return } setError(''); setStatus('loading'); try { await new Promise(resolve => setTimeout(resolve, 650)); /* Future API integration belongs here. */ setStatus('success'); form.reset() } catch { setStatus('error') } }
  if (status === 'success') return <div className="form-message success"><Check size={24} /><h3>Thanks for reaching out.</h3><p>Your information stayed in this browser and was not transmitted. This local form is ready to connect to a future API endpoint.</p><button className="button button-dark" onClick={() => setStatus('idle')}>Send another inquiry</button></div>
  return <form className="contact-form" onSubmit={submitProjectInquiry} noValidate><div className="form-grid"><label>Full name *<input name="name" required placeholder="Your name" /></label><label>Company name<input name="company" placeholder="Your company" /></label><label>Business email *<input name="email" type="email" required placeholder="name@company.com" /></label><label>Phone number<input name="phone" type="tel" placeholder="[Business phone]" /></label><label>Industry<select name="industry" defaultValue=""><option value="" disabled>Select an industry</option>{industries.map(i => <option key={i.title}>{i.title}</option>)}</select></label><label>Service needed<select name="service" defaultValue=""><option value="" disabled>Select a service</option>{services.map(s => <option key={s.title}>{s.title}</option>)}</select></label><label>Estimated budget range<select name="budget" defaultValue=""><option value="">Select a range</option><option>$10k – $50k</option><option>$50k – $150k</option><option>$150k+</option><option>Not sure yet</option></select></label><label>Desired timeline<select name="timeline" defaultValue=""><option value="">Select a timeline</option><option>Exploring</option><option>1–3 months</option><option>3–6 months</option><option>6+ months</option></select></label><label className="full-width">Project description *<textarea name="description" required rows={5} placeholder="What is changing, and what would better look like?"></textarea></label><label>Preferred contact method<select name="contact" defaultValue="Email"><option>Email</option><option>Phone</option></select></label></div><label className="checkbox"><input type="checkbox" required /> <span>I agree to the <Link to="/privacy">Privacy Policy</Link>. *</span></label>{error && <p className="form-error" role="alert">{error}</p>}{status === 'error' && <p className="form-error" role="alert">Something went wrong. Please try again.</p>}<button className="button button-dark" disabled={status === 'loading'}>{status === 'loading' ? 'Sending locally…' : 'Send project inquiry'} <ArrowUpRight size={17} /></button></form>
}

export function Layout({ children }: { children: ReactNode }) { const { pathname } = useLocation(); window.scrollTo(0, 0); return <><Header /><main id="main" key={pathname}>{children}</main><Footer /></> }
