export type Service = { title: string; description: string; icon: string; bullets: string[] }
export type ArticleSection = { heading: string; text: string }
export type Article = { slug: string; title: string; category: string; excerpt: string; date: string; readTime: string; sections: ArticleSection[] }
export type TeamMember = { name: string; role: string; focus: string; bio: string; leadership: boolean }

export const services: Service[] = [
  { title: 'Custom Software Engineering', description: 'Translate operating priorities into durable digital capabilities that fit the way work is governed, measured, and improved.', icon: 'code', bullets: ['Operating-model and workflow analysis', 'Enterprise applications and APIs', 'Role, data, and decision design', 'Legacy capability modernization', 'Quality, controls, and lifecycle planning'] },
  { title: 'ERP Solutions', description: 'Align finance, supply chain, people, and operational data around a shared management system and a practical adoption plan.', icon: 'layers', bullets: ['ERP strategy and readiness assessment', 'Process, requirements, and governance design', 'Platform evaluation and implementation', 'Data ownership, migration, and controls', 'Change enablement and post-launch improvement'] },
  { title: 'Systems Integration', description: 'Create an integrated operating environment so critical information moves across functions without losing context, accountability, or control.', icon: 'link', bullets: ['ERP, CRM, finance, and commerce integration', 'Plant, warehouse, field, and operational systems', 'API and middleware architecture', 'Master data and synchronization rules', 'Integration observability and ownership'] },
  { title: 'Cloud and DevOps', description: 'Build delivery and infrastructure practices that support continuity, responsible investment, and a technology estate the organization can operate.', icon: 'cloud', bullets: ['Technology estate and cloud-readiness review', 'Resilient architecture and migration planning', 'Release governance and CI/CD pipelines', 'Infrastructure automation and standards', 'Monitoring, recovery, and operational resilience'] },
  { title: 'Data and Business Intelligence', description: 'Give leaders and operating teams a consistent view of performance, risk, capacity, and the drivers behind results.', icon: 'chart', bullets: ['Management information architecture', 'Data integration and governed pipelines', 'Operational and executive reporting', 'Power BI dashboards and performance measures', 'Data ownership, quality, and governance'] },
  { title: 'AI and Business Automation', description: 'Apply automation where it strengthens throughput, consistency, and employee capacity while preserving accountability and human judgment.', icon: 'spark', bullets: ['Workflow and document automation', 'AI-assisted research and knowledge access', 'Exception routing and intelligent notifications', 'Human-in-the-loop operating controls', 'Responsible AI evaluation and adoption'] },
  { title: 'Managed Technology Support', description: 'Provide the stewardship, documentation, and operating cadence required to keep business-critical systems useful over time.', icon: 'shield', bullets: ['Application and ERP operating support', 'Incident, change, and release coordination', 'Integration ownership and service reviews', 'Performance and capability assessments', 'Runbooks, documentation, and knowledge transfer'] },
]

export const industries = [
  { title: 'Automotive', description: 'Coordinate dealership, service, parts, inventory, and finance operations around a clearer customer and asset lifecycle.' },
  { title: 'Retail & E-commerce', description: 'Connect commercial, inventory, customer, and fulfillment decisions across channels and business units.' },
  { title: 'Distribution & Logistics', description: 'Improve flow, traceability, planning, and accountability across warehouses, orders, carriers, and suppliers.' },
  { title: 'Manufacturing', description: 'Link production, procurement, quality, maintenance, and inventory decisions to the operating plan.' },
  { title: 'Professional Services', description: 'Align delivery capacity, project economics, knowledge, billing, and client visibility with the operating model.' },
  { title: 'Financial Services', description: 'Strengthen internal control, workflow accountability, reporting, integration, and information governance.' },
]

export const processSteps = [
  ['Discover', 'Clarify strategic priorities, operating constraints, decision rights, stakeholder needs, and the measures that define progress.'],
  ['Plan', 'Translate priorities into a sequenced portfolio of initiatives, practical options, investment assumptions, risks, and ownership.'],
  ['Design', 'Design the target operating experience, information model, controls, integration architecture, and adoption approach.'],
  ['Build', 'Configure and develop in accountable increments, with transparent tradeoffs, testing, documentation, and stakeholder feedback.'],
  ['Launch', 'Prepare people, data, governance, support, and operational ownership so the change can move into business-as-usual.'],
  ['Improve', 'Review performance, adoption, risk, and capacity regularly to refine the system and the organization around it.'],
]

export const articles: Article[] = [
  { slug: 'when-your-business-needs-an-erp', title: 'How to Know When Your Business Needs an ERP System', category: 'Operating Model', excerpt: 'Recognize when fragmented systems are preventing consistent decisions, accountability, and scalable growth.', date: 'September 2026', readTime: '6 min read', sections: [{ heading: 'Look for operating friction', text: 'An ERP conversation is usually justified when teams spend too much time reconciling spreadsheets, re-entering orders, or explaining why reports disagree. The issue is not simply that systems are old; it is that the current operating model cannot provide a dependable view of commitments, costs, inventory, or capacity.' }, { heading: 'Test the business case before choosing a platform', text: 'Map the decisions that are currently slow or unreliable, then connect each one to a measurable improvement. Assess process ownership, data quality, integration needs, user adoption, and the organization\'s ability to support a shared system before comparing vendors.' }, { heading: 'Treat ERP as a management system', text: 'A successful ERP program changes how work is governed, not only where transactions are recorded. Establish executive sponsorship, process owners, a realistic implementation sequence, and a plan for continuous improvement after launch.' }] },
  { slug: 'erp-implementation-risks', title: 'ERP Implementation Risks and How to Reduce Them', category: 'Transformation', excerpt: 'Manage scope, ownership, adoption, data, and decision-making risks before they become program constraints.', date: 'August 2026', readTime: '7 min read', sections: [{ heading: 'Scope follows decisions', text: 'ERP programs become unstable when every department adds requirements without a clear decision framework. Define the target operating model, the outcomes that matter, and the principles that will guide configuration choices before the backlog becomes a substitute for strategy.' }, { heading: 'Data and adoption are delivery work', text: 'Migration quality, role design, training, and business readiness cannot be left to the end. Assign owners for critical data and processes, test realistic scenarios, and give users a visible path to raise issues and understand how the new system changes their work.' }, { heading: 'Build governance into the cadence', text: 'A steady implementation rhythm includes decision logs, risk reviews, scope controls, integrated testing, and clear escalation paths. These practices help leaders resolve tradeoffs quickly while keeping the program connected to business value.' }] },
  { slug: 'custom-software-vs-off-the-shelf', title: 'Custom Software vs. Off-the-Shelf Solutions', category: 'Technology Strategy', excerpt: 'Evaluate fit, control, speed, total cost, and organizational capability before choosing an investment path.', date: 'August 2026', readTime: '5 min read', sections: [{ heading: 'Start with the capability', text: 'The right question is not whether custom software is better than a packaged product. First define the capability, users, decisions, controls, and differentiators the organization needs to support.' }, { heading: 'Compare the full tradeoff', text: 'Packaged software can accelerate common processes but may require adaptation, integration, or ongoing configuration. Custom software can fit a distinctive workflow more closely but creates responsibility for architecture, security, support, and product evolution.' }, { heading: 'Choose what the organization can sustain', text: 'Evaluate total cost, delivery speed, vendor dependency, internal skills, data ownership, and change frequency. A smaller configurable solution may be the best first step when it solves the highest-value constraint without creating unnecessary platform complexity.' }] },
  { slug: 'systems-integration-reduces-manual-work', title: 'How Systems Integration Reduces Manual Work', category: 'Connected Operations', excerpt: 'Find the handoffs, ownership gaps, and information delays that limit operating performance.', date: 'July 2026', readTime: '5 min read', sections: [{ heading: 'Find the handoffs before automating them', text: 'Manual work often hides at the boundaries between sales, finance, operations, warehouses, and service teams. Trace a transaction from its origin to its final decision and document every re-entry, approval, delay, and exception.' }, { heading: 'Connect meaning, not just endpoints', text: 'An integration is useful when systems share consistent definitions, ownership, validation rules, and timing expectations. APIs and middleware cannot resolve conflicting business meanings by themselves.' }, { heading: 'Measure the flow after launch', text: 'Track processing time, exception volume, rework, failed synchronizations, and the time required to resolve issues. Assign operational ownership so integrations remain observable and useful as processes change.' }] },
  { slug: 'legacy-application-modernization', title: 'A Practical Guide to Legacy Application Modernization', category: 'Organizational Capability', excerpt: 'Modernize without discarding the business knowledge, controls, and continuity embedded in existing systems.', date: 'July 2026', readTime: '8 min read', sections: [{ heading: 'Understand what the legacy system knows', text: 'Long-lived applications often contain valuable rules, exceptions, reports, and controls that are not documented anywhere else. Inventory critical workflows and dependencies before deciding what to replace, wrap, rehost, or retire.' }, { heading: 'Modernize in capability increments', text: 'Choose a bounded business capability with a clear owner and measurable outcome. Strangler patterns, service extraction, data synchronization, and focused user experiences can reduce risk while the broader platform evolves.' }, { heading: 'Protect continuity while changing the platform', text: 'Use parallel validation, observability, rollback plans, security reviews, and knowledge transfer to make change reversible where possible. Modernization succeeds when the organization gains a stronger way to operate, not simply a newer technology stack.' }] },
  { slug: 'preparing-data-for-erp-migration', title: 'Preparing Business Data for an ERP Migration', category: 'Data Governance', excerpt: 'Establish ownership, definitions, quality standards, and decision confidence before migration begins.', date: 'June 2026', readTime: '6 min read', sections: [{ heading: 'Assign ownership before cleansing', text: 'Data quality is a business responsibility. Identify owners for customers, products, suppliers, accounts, locations, and other critical objects before asking a project team to clean records.' }, { heading: 'Define what good data means', text: 'Create shared definitions, required fields, validation rules, duplicate policies, and retention expectations. Profile the source data to understand completeness, inconsistency, obsolete records, and hidden dependencies.' }, { heading: 'Reconcile with business scenarios', text: 'Do not validate migrated data only through technical counts. Test order, purchase, inventory, financial, and reporting scenarios with business owners so the new system supports the decisions and controls people rely on.' }] },
]

export const team: TeamMember[] = [
  { name: 'Muhammad Arsalan', role: 'CEO', focus: 'Strategy and operating models', bio: 'Helps leadership teams turn ambitious priorities into practical operating choices, accountable roadmaps, and measurable change.', leadership: true },
  { name: 'Ethan Brooks', role: 'CTO', focus: 'Architecture and modernization', bio: 'Connects technology portfolios, platform decisions, and delivery discipline so organizations can modernize without losing continuity.', leadership: true },
  { name: 'Priya Shah', role: 'COO', focus: 'Transformation and execution', bio: 'Creates the delivery rhythm, decision visibility, and stakeholder alignment needed to move complex initiatives into operation.', leadership: true },
  { name: 'Daniel Kim', role: 'Director, Data and Automation', focus: 'Data products and responsible AI', bio: 'Designs governed information and human-centered automation that improves decisions while keeping ownership and controls clear.', leadership: true },
  { name: 'Avery Wilson', role: 'Principal Consultant', focus: 'ERP and business process', bio: 'Maps the connection between finance, operations, and systems to make ERP investments more useful to the people running the business.', leadership: false },
  { name: 'Noah Patel', role: 'Solution Architect', focus: 'Integration and cloud', bio: 'Builds resilient integration patterns and cloud foundations that help information move with context, security, and accountability.', leadership: false },
  { name: 'Sofia Bennett', role: 'Engagement Lead', focus: 'Adoption and capability', bio: 'Brings teams into the work early, translating new processes and systems into habits people can understand and sustain.', leadership: false },
  { name: 'Alexander Mathis', role: 'Senior Software Engineer', focus: 'Digital products and delivery', bio: 'Turns well-framed business needs into dependable software, with attention to quality, usability, and the realities of day-to-day operations.', leadership: false },
]
